name: Docker Images

on:
  push:
    branches: ['main']

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - run: ./util/build

